# Generated by Django 5.1.4 on 2024-12-25 06:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0002_initial'),
        ('budgetItem', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetailUsage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('planned_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('advanced_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('settled_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('remaining_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('note', models.TextField(blank=True, null=True)),
                ('due_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detail_usages', to='account.account')),
                ('budget_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detail_usages', to='budgetItem.budgetitem')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_detail_usages', to='account.account')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_detail_usages', to='account.account')),
            ],
        ),
    ]
